### ISSUE TITLE
Build error in ngs-java: wrong working directory

### ISSUE THREAD

**Issue by lexming** [ncbi/sra-tools#771] opened 2023-02-09 16:04 UTC
Build fails due to a non-existent `obj` directory injected in the working directory path of `ngs-doc_javadoc`: 

```
[ 37%] Built target ngs-doc_javadoc
make  -f ngs/ngs-java/CMakeFiles/ngs-doc-jar.dir/build.make ngs/ngs-java/CMakeFiles/ngs-doc-jar.dir/depend
make[2]: Entering directory `/theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj'
cd /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj && /vscmnt/brussel_pixiu_apps/_apps_brussel/CO7/skylake/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/sra-tools-3.0.3 /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/sra-tools-3.0.3/ngs/ngs-java /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj/ngs/ngs-java /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj/ngs/ngs-java/CMakeFiles/ngs-doc-jar.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj'
make  -f ngs/ngs-java/CMakeFiles/ngs-doc-jar.dir/build.make ngs/ngs-java/CMakeFiles/ngs-doc-jar.dir/build
make[2]: Entering directory `/theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj'
cd /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj/obj/ngs/ngs-java/javadoc/ngs-doc && bash -c /apps/brussel/CO7/skylake/software/Java/11.0.16/bin/jar\ -cf\ /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj/lib/ngs-doc.jar\ .
/bin/sh: line 0: cd: /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj/obj/ngs/ngs-java/javadoc/ngs-doc: No such file or directory
make[2]: *** [ngs/ngs-java/CMakeFiles/ngs-doc-jar] Error 1
make[2]: Leaving directory `/theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj'
make[1]: *** [ngs/ngs-java/CMakeFiles/ngs-doc-jar.dir/all] Error 2
make[1]: Leaving directory `/theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/easybuild_obj'
make: *** [all] Error 2
```

Build environment:
* GCC v11.3.0
* CMake v3.23.1

CMake command:
```
cmake  -DCMAKE_INSTALL_PREFIX=/user/brussel/101/vsc10122/easybuild/install/skylake/software/SRA-Toolkit/3.0.3-gompi-2022a -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DVDB_INCDIR="$EBROOTNCBIMINVDB/include" -DVDB_LIBDIR="$EBROOTNCBIMINVDB/lib"  /theia/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/skylake/build/SRAToolkit/3.0.3/gompi-2022a/sra-tools-3.0.3/
```

**Comment by aboshkin** [comment] 2023-02-09 20:46
@lexming thank you for submitting the PR! We will investigate and make sure the issue is fixed in the next release.

**Comment by klymenko** [comment] 2023-05-10 18:07
@lexming, this issue is fixed in our latest release.

**Closed** 2023-07-13 17:34 UTC
