### ISSUE TITLE
fasterq-dump error 

### ISSUE THREAD

**Issue by Gin-Wang** [ncbi/sra-tools#336] opened 2020-05-28 01:52 UTC
i am using the lateast version of sratoolkit 2.10.7 in centOS7, but it failed.i used to use 2.10.0 and never met this. Yesterday when i do it for SRR6039353-SRR6039355 it shows error, so I check the issue and it shows that update sratoolkit may help and I update my sratoolkit to v2.10.7 but it still eroor.
~~~
fasterq-dump -e 8 --split-3 0.sra_data/SRR6039354.sra -O ./1.raw_data -t ./tmp

2020-05-28T01:40:10 fasterq-dump.2.10.7 err: cmn_iter.c cmn_iter_open_db().VDBManagerOpenDBRead( 'SRR6039354.sra' ) -> RC(rcVFS,rcMgr,rcOpening,rcDirectory,rcNotFound) 
2020-05-28T01:40:10 fasterq-dump.2.10.7 err: sorter.c run_producer_pool(): row_count == 0!
2020-05-28T01:40:10 fasterq-dump.2.10.7 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
2020-05-28T01:40:10 fasterq-dump.2.10.7 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
fasterq-dump quit with error code 3
~~~

by the way, if i use this commond it will start download something and other sra files would not. and '--split-3' shows "unrecognized option: '--split-3'".
~~~
fastq-dump -O ./1.raw_data ./0.sra_data/SRR6039353.sra
~~~

best!

**Comment by klymenko** [comment] 2020-05-28 16:02
@Gin-Wang , do you get this error immediately?

**Comment by Gin-Wang** [comment] 2020-05-29 05:15
> @Gin-Wang , do you get this error immediately?
yes, in about 1 or 2 seconds.

**Comment by klymenko** [comment] 2020-05-29 18:50
@Gin-Wang , SRR6039354 requires 22 reference sequences.

Recommended way to get fastq-dump:

prefetch SRR6039354 && fasterq-dump [options] SRR6039354

**Comment by matrs** [comment] 2020-05-31 14:40
```bash
$ fastq-dump SRR9827746 --split-3
unrecognized option: '--split-3'

$ fastq-dump --version

"fastq-dump" version 2.10.3
```
?

**Comment by chrstraub** [comment] 2020-06-22 01:12
I have the same problem after using prefetch:

```
fastq-dump ERR2650458.sra --split-3 --skip-technical --readids --read-filter pass --dumpbase --clip SRR_ID

unrecognized option: '--split-3'

version:
/sratoolkit.2.10.7-ubuntu64/
"fastq-dump version 2.10.7"


```

**Comment by helloicyvodka** [comment] 2020-07-08 02:13
perhaps we should use the option "--split-e"

**Comment by durbrow** [comment] 2020-07-22 02:28
This will been fixed in the next release. https://github.com/ncbi/sra-tools/issues/381#issuecomment-658858327 If you have modified any scripts/pipelines to use `--split-e`, do not fret, `--split-e` will be a silent alias of `--split-3`.

**Comment by jiewang0813** [comment] 2020-08-07 14:18
You should use split-e

**Comment by durbrow** [comment] 2020-08-07 14:25
You should only use `--split-e` as a temporary fix. It is a typo that will be fixed in the next release. `--split-e` will continue to work for some time, but it will be deprecated and will not show up in the help text for `fastq-dump`. It is likely that `--split-e` will be removed at some point.

**Comment by klymenko** [comment] 2020-12-23 17:08
Have you tried `-split-3`? This bug was fixed.

**Closed** 2020-12-28 20:23 UTC

**Comment by Hassan2021512** [comment] 2022-04-21 01:39
Hi, I am trying to split the RNA-seq file and facing the problem mentioned below. Can anyone help regarding this issue? Thanks
(base) user@user:~/Downloads$ fasterq-dump --gzip --split-file SRR8885553
2022-04-21T01:14:44 fasterq-dump.2.9.1 err: param unknown while parsing argument list within application support module - Unknown argument '--gzip'
2022-04-21T01:14:44 fasterq-dump.2.9.1 err: param unknown while parsing argument list within application support module - Unknown argument '--split-file'
2022-04-21T01:14:44 fasterq-dump.2.9.1 err: ArgsMakeAndHandle() -> RC(rcApp,rcArgv,rcParsing,rcParam,rcUnknown)

**Comment by wraetz** [comment] 2022-04-21 13:17
The problem is that you are applying fastq-dump options to fasterq-dump. They do not take the same options.
'fasterq-dump -h' lists all valid options. At the end of the help-text are 2 links explaining fasterq-dump in more detail.
In your case: fasterq-dump does not support '--gzip' or '--bzip'. You have to compress the files manually after the tool is finished. The options '--split-file' is named '--split-files'.
