### ISSUE TITLE
fasterq-dump crashes with exit code 3 on some SRAs

### ISSUE THREAD

**Issue by danieldanciu** [ncbi/sra-tools#318] opened 2020-04-29 18:21 UTC
We are trying to construct a gigantic index of all eukaryotes. As a first step, we wanted to do a test run on all Fungi. We were able to successfully download and process about 65TB out of the ~90TB of Fungi SRAs. However, we are not able to download the remaining ~25TB. These are mostly BAM/CRAM files that need a reference file. The reason we can't download the remaining 25TB is that fasterq-dump crashes with exit code 3, and not much information:
```
fasterq-dump /tmp/DRR121635.1 -f -e 1 -O /tmp/DRR121635/ -t /tmp/do -m 1G
2020-04-29T18:13:08 fasterq-dump.2.10.5 err: row#90336 : bits=32, boff=0, len=0
2020-04-29T18:13:09 fasterq-dump.2.10.5 err: row#23552 : bits=32, boff=0, len=0
fasterq-dump (PID 38076) quit with error code 3
```
The error is always reproducible, both on my Mac and on the Cloud Linux boxes.
Any ideas what could be wrong? 
Note that the crash also happens if we simply run:
  `fasterq-dump DRR121635`
and allow the tool to download the SRA file rather than copying it from the cloud storage.

There is plenty of free disk space on the system (the SRA is quite small) and 1024 file descriptors are available. When running against the local SRA file, the crash happens in a few seconds.

Tool version: 2.10.5
Reproduced on: Ubuntu 18.04, Mac 10.15.3

Any help appreciated!

**Comment by wraetz** [comment] 2020-04-29 19:56
I can reproduce the error you are encountering. It looks like the problem is that there are 5 rows in this run that have no data... ( len=0 ) We are investigating the problem...
Please use fastq-dump instead of fasterq-dump on these runs.

**Comment by danieldanciu** [comment] 2020-04-30 07:20
Thanks for the quick reply. If there is an easy patch for the issue, I am happy to apply it and recompile in order to have this tool working. Alternatively, if you can point me to the relevant section of code, I can attempt to fix it myself.

Unfortunately `fastq-dump` also failed with a similar error:
```
fastq-dump /mnt/disks/ssd/downloads/ERR3084882/sra/ERR3084882.1  -O /mnt/disks/ssd/downloads/ERR3084882/fastq --fasta default
2020-04-30T07:05:04 fastq-dump.2.10.4 err: name not found while resolving query within virtual file system module - failed to resolve accession '/mnt/disks/ssd/downloads/ERR3084882/sra/ERR3084882.1' - Cannot resolve accession ( 404 )
2020-04-30T07:10:19 fastq-dump.2.10.4 err: data corrupt while selecting function within transform module - failed /mnt/disks/ssd/downloads/ERR3084882/sra/ERR3084882.1

=============================================================
An error occurred during processing.
A report was generated into the file '/home/ddanciu/ncbi_error_report.txt'.
If the problem persists, you may consider sending the file
to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
=============================================================

fastq-dump (PID 22764) quit with error code 3
```

The contents of the error file is:
```
<Report>
 <Run>
  <Date>
   <Start value="Thu Apr 30 2020 7:05:04 AM"/>
   <End value="Thu Apr 30 2020 7:10:19 AM"/>
  </Date>
  <Home name="HOME" value="/home/ddanciu"/>
  <Cwd>/mnt/disks/ssd</Cwd>
  <CommandLine argc="5">
   <Arg index="0" value="/usr/local/ncbi/sra-tools/bin/fastq-dump"/>
   <Arg index="1" value="-O"/>
   <Arg index="2" value="/mnt/disks/ssd/downloads/ERR3084882/fastq"/>
   <Arg index="3" value="--fasta"/>
   <Arg index="4" value="/mnt/disks/ssd/downloads/ERR3084882/sra/ERR3084882.1"/>
  </CommandLine>
  <Result rc="RC(rcXF,rcFunction,rcSelecting,rcData,rcCorrupt)"/>
  <User admin="false"/>
 </Run>
 <Configuration>
  <Files count="4">
   <File name="/etc/ncbi/certs.kfg"/>
   <File name="/etc/ncbi/default.kfg"/>
   <File name="/etc/ncbi/vdb-copy.kfg"/>
   <File name="/home/ddanciu/.ncbi/user-settings.mkfg"/>
  </Files>
  <refseq state="not found"/>
  <krypto state="pwfile: not found"/>
  <sra state="not found"/>
  <Config>
  <ConfigurationFiles>
/etc/ncbi/certs.kfg
/etc/ncbi/default.kfg
/etc/ncbi/vdb-copy.kfg
/home/ddanciu/.ncbi/user-settings.mkfg
    </ConfigurationFiles>
    <APPNAME>"fastq-dump"</APPNAME>
    <APPPATH>"/usr/local/ncbi/sra-tools/bin"</APPPATH>
    <AWS></AWS>
    <BUILD>"RELEASE"</BUILD>
    <HOME>"/home/ddanciu"</HOME>
    <HOST></HOST>
    <LIBS>
      <GUID>"b5e8809a-a4dd-4099-b07a-84b625db2a1f"</GUID>
    </LIBS>
    <NCBI_HOME>"/home/ddanciu/.ncbi"</NCBI_HOME>
    <NCBI_SETTINGS>"/home/ddanciu/.ncbi/user-settings.mkfg"</NCBI_SETTINGS>
    <OS>"linux"</OS>
    <PWD>"/mnt/disks/ssd"</PWD>
    <USER>"ddanciu"</USER>
    <VDBCOPY>
      <DO_NOT_REDACT>"CS_KEY,FLOW_CHARS,KEY_SEQUENCE,LINKER_SEQUENCE"</DO_NOT_REDACT>
      <META>
        <IGNORE>"col,.seq,STATS,BASE_COUNT,HUFFMAN_TREE_POS,HUFFMAN_TREE_POS_SIZE,HUFFMAN_TREE_PRB,HUFFMAN_TREE_PRB_SIZE,HUFFMAN_TREE_SIG,HUFFMAN_TREE_SIG_SIZE,MSC454_CLIP_QUALITY_LEFT,MSC454_CLIP_QUALITY_RIGHT,MSC454_FLOW_CHARS,MSC454_KEY_SEQUENCE,NREADS,NUMBER_POS_CHANNELS,NUMBER_PRB_CHANNELS_1,NUMBER_PRB_COLUMNS,NUMBER_SIG_CHANNELS,PLATFORM,READ_0,READ_1,SPOT_COUNT"</IGNORE>
      </META>
      <NCBI_SRA_ABI_tbl_v1_1>
        <schema>"sra/abi.vschema"</schema>
        <tab>"NCBI:SRA:ABI:tbl:v2"</tab>
      </NCBI_SRA_ABI_tbl_v1_1>
      <NCBI_SRA_Illumina_tbl_v0a_1>
        <schema>"sra/illumina.vschema"</schema>
        <tab>"NCBI:SRA:Illumina:tbl:phred:v2"</tab>
      </NCBI_SRA_Illumina_tbl_v0a_1>
      <NCBI_SRA__454__tbl_v0_1>
        <schema>"sra/454.vschema"</schema>
        <tab>"NCBI:SRA:_454_:tbl:v2"</tab>
      </NCBI_SRA__454__tbl_v0_1>
      <READ_FILTER_COL_NAME>"READ_FILTER"</READ_FILTER_COL_NAME>
      <REDACTABLE_TYPES>"INSDC:color:text,INSDC:x2cs:bin,INSDC:2cs:bin,INSDC:2cs:packed,INSDC:dna:text,INSDC:4na:bin,INSDC:4na:packed,INSDC:x2na:bin,INSDC:2na:bin,INSDC:2na:packed,NCBI:SRA:pos16,INSDC:quality:phred,INSDC:quality:log_odds,NCBI:qual4,INSDC:position:one,INSDC:position:zero,NCBI:fsamp4,NCBI:isamp1"</REDACTABLE_TYPES>
      <REDACTVALUE>
        <INSDC_color_text>
          <VALUE>"'.'"</VALUE>
        </INSDC_color_text>
        <INSDC_dna_text>
          <VALUE>"'N'"</VALUE>
        </INSDC_dna_text>
        <NCBI_qual4>
          <VALUE>"-6"</VALUE>
        </NCBI_qual4>
        <TYPES>"INSDC_color_text,INSDC_dna_text,NCBI_qual4"</TYPES>
      </REDACTVALUE>
      <SCORE>
        <INSDC_2cs_bin>"2"</INSDC_2cs_bin>
        <INSDC_2cs_packed>"2"</INSDC_2cs_packed>
        <INSDC_2na_bin>"2"</INSDC_2na_bin>
        <INSDC_2na_packed>"2"</INSDC_2na_packed>
        <INSDC_SRA_read_type>"1"</INSDC_SRA_read_type>
        <INSDC_quality_log_odds>"1"</INSDC_quality_log_odds>
        <INSDC_quality_phred>"1"</INSDC_quality_phred>
        <INSDC_x2cs_bin>"1"</INSDC_x2cs_bin>
        <INSDC_x2na_bin>"1"</INSDC_x2na_bin>
      </SCORE>
      <_454_>
        <schema>"sra/454.vschema"</schema>
        <tab>"NCBI:SRA:_454_:tbl:v2"</tab>
      </_454_>
      <_ABSOLID_>
        <schema>"sra/abi.vschema"</schema>
        <tab>"NCBI:SRA:ABI:tbl:v2"</tab>
      </_ABSOLID_>
      <_ILLUMINA_>
        <schema>"sra/illumina.vschema"</schema>
        <tab>"NCBI:SRA:Illumina:tbl:phred:v2"</tab>
      </_ILLUMINA_>
    </VDBCOPY>
    <VDB_CONFIG></VDB_CONFIG>
    <VDB_ROOT></VDB_ROOT>
    <config>
      <default>"false"</default>
    </config>
    <kfg>
      <arch>
        <bits>"64"</bits>
        <name>"mg-fungi-2"</name>
      </arch>
      <dir>"/home/ddanciu/.ncbi"</dir>
      <name>"user-settings.mkfg"</name>
    </kfg>
    <libs>
      <cache_amount>"100"</cache_amount>
      <cloud>
        <report_instance_identity>"true"</report_instance_identity>
      </cloud>
    </libs>
    <repository>
      <remote>
        <main>
          <CGI>
            <resolver-cgi>"https://trace.ncbi.nlm.nih.gov/Traces/names/names.fcgi"</resolver-cgi>
          </CGI>
          <SDL.2>
            <resolver-cgi>"https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve"</resolver-cgi>
          </SDL.2>
        </main>
        <protected>
          <CGI>
            <resolver-cgi>"https://trace.ncbi.nlm.nih.gov/Traces/names/names.fcgi"</resolver-cgi>
          </CGI>
          <SDL.2>
            <resolver-cgi>"https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve"</resolver-cgi>
          </SDL.2>
        </protected>
      </remote>
      <user>
        <ad>
          <public>
            <apps>
              <file>
                <volumes>
                  <flat>"."</flat>
                </volumes>
              </file>
              <refseq>
                <volumes>
                  <refseqAd>"."</refseqAd>
                </volumes>
              </refseq>
              <sra>
                <volumes>
                  <sraAd>"."</sraAd>
                </volumes>
              </sra>
              <sraPileup>
                <volumes>
                  <ad>"."</ad>
                </volumes>
              </sraPileup>
              <sraRealign>
                <volumes>
                  <ad>"."</ad>
                </volumes>
              </sraRealign>
            </apps>
            <root>"."</root>
          </public>
        </ad>
        <default-path>"/home/ddanciu/ncbi"</default-path>
        <main>
          <public>
            <apps>
              <file>
                <volumes>
                  <flat>"files"</flat>
                </volumes>
              </file>
              <nakmer>
                <volumes>
                  <nakmerFlat>"nannot"</nakmerFlat>
                </volumes>
              </nakmer>
              <nannot>
                <volumes>
                  <nannotFlat>"nannot"</nannotFlat>
                </volumes>
              </nannot>
              <refseq>
                <volumes>
                  <refseq>"refseq"</refseq>
                </volumes>
              </refseq>
              <sra>
                <volumes>
                  <sraFlat>"sra"</sraFlat>
                </volumes>
              </sra>
              <sraPileup>
                <volumes>
                  <withExtFlat>"sra"</withExtFlat>
                </volumes>
              </sraPileup>
              <sraRealign>
                <volumes>
                  <withExtFlat>"sra"</withExtFlat>
                </volumes>
              </sraRealign>
              <wgs>
                <volumes>
                  <wgsFlat>"wgs"</wgsFlat>
                </volumes>
              </wgs>
            </apps>
            <root>"/mnt/disks/ssd/fasterqtmp"</root>
          </public>
        </main>
      </user>
    </repository>
    <tls>
      <ca.crt>
        <ncbi1>"-----BEGIN CERTIFICATE-----\x0D\x0AMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\x0D\x0AMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\x0D\x0Ad3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\x0D\x0AQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\x0D\x0AMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\x0D\x0Ab20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\x0D\x0A9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\x0D\x0ACSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\x0D\x0Anh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\x0D\x0A43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\x0D\x0AT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\x0D\x0AgdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\x0D\x0ABgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\x0D\x0ATLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\x0D\x0ADQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\x0D\x0AhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\x0D\x0A06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\x0D\x0APnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\x0D\x0AYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\x0D\x0ACAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4wOTAeBggrBgEFBQcD\x0D\x0ABAYIKwYBBQUHAwEGCCsGAQUFBwMDDBdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQQ==\x0D\x0A-----END CERTIFICATE-----\x0D\x0A"</ncbi1>
        <ncbi2>"-----BEGIN CERTIFICATE-----\x0D\x0AMIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs\x0D\x0AMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\x0D\x0Ad3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j\x0D\x0AZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL\x0D\x0AMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3\x0D\x0ALmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug\x0D\x0ARVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm\x0D\x0A+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW\x0D\x0APNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM\x0D\x0AxChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB\x0D\x0AIk5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3\x0D\x0AhzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg\x0D\x0AEsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF\x0D\x0AMAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA\x0D\x0AFLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec\x0D\x0AnzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z\x0D\x0AeM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF\x0D\x0AhS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2\x0D\x0AYzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe\x0D\x0AvEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep\x0D\x0A+OkuE6N36B9KMEQwHgYIKwYBBQUHAwQGCCsGAQUFBwMBBggrBgEFBQcDAwwiRGln\x0D\x0AaUNlcnQgSGlnaCBBc3N1cmFuY2UgRVYgUm9vdCBDQQ==\x0D\x0A-----END CERTIFICATE-----\x0D\x0A"</ncbi2>
      </ca.crt>
    </tls>
    <tools>
      <ascp>
        <max_rate>"450m"</max_rate>
      </ascp>
    </tools>
    <vdb>
      <lib>
        <paths>
          <kfg>"/usr/local/ncbi/sra-tools/bin"</kfg>
        </paths>
      </lib>
    </vdb>
  </Config>
  <RemoteAccess available="true"/>
  <CurrentProtectedRepository found="false"/>
 </Configuration>
 <Object path="/mnt/disks/ssd/downloads/ERR3084882/sra/ERR3084882.1" type="database" fs_type="archive" size="26685865">
  <Dependencies>
   <List count="17" missing="5">
    <Dependency index="0" seq_id="NC_001133.7" local="true" path=""/>
    <Dependency index="1" seq_id="NC_001134.7" local="true" path=""/>
    <Dependency index="2" seq_id="NC_001135.4" local="true" path=""/>
    <Dependency index="3" seq_id="NC_001136.8" local="false" path=""/>
    <Dependency index="4" seq_id="NC_001137.2" local="true" path=""/>
    <Dependency index="5" seq_id="NC_001138.4" local="true" path=""/>
    <Dependency index="6" seq_id="NC_001139.7" local="false" path=""/>
    <Dependency index="7" seq_id="NC_001140.5" local="true" path=""/>
    <Dependency index="8" seq_id="NC_001141.1" local="true" path=""/>
    <Dependency index="9" seq_id="NC_001142.7" local="true" path=""/>
    <Dependency index="10" seq_id="NC_001143.7" local="true" path=""/>
    <Dependency index="11" seq_id="NC_001144.4" local="false" path=""/>
    <Dependency index="12" seq_id="NC_001145.2" local="true" path=""/>
    <Dependency index="13" seq_id="NC_001146.6" local="true" path=""/>
    <Dependency index="14" seq_id="NC_001147.5" local="false" path=""/>
    <Dependency index="15" seq_id="NC_001148.3" local="true" path=""/>
    <Dependency index="16" seq_id="NC_001224.1" local="false" path=""/>
   </List>
  </Dependencies>
 </Object>
 <SOFTWARE>
  <VDBLibrary vers="2.7.36"/>
  <Build static="true">
   <Module name=""/>
  </Build>
  <Tool date="Feb 25 2020" name="/usr/local/ncbi/sra-tools/bin/fastq-dump" vers="2.10.4">
   <Binary path="/usr/local/ncbi/sra-tools/bin/fastq-dump" type="alias" md5="6915ae9c3296b859ffc01bfe3dcb052b">
    <Alias resolved="fastq-dump.2">
     <Alias resolved="fastq-dump.2.10.4">
      <Alias resolved="sratools.2.10.4"/>
     </Alias>
    </Alias>
   </Binary>
  </Tool>
 </SOFTWARE>
 <Env>
 </Env>
</Report>
```

**Comment by isidroc** [comment] 2020-05-09 22:52
Same problems here. Any news? Thanks

**Comment by wajm** [comment] 2020-05-11 06:27
Same problems here. 

2020-05-11T06:10:13 fastq-dump.2.10.5 err: timeout exhausted while waiting condition within process system module - failed SRR8452033

=============================================================
An error occurred during processing.
A report was generated into the file '/Users/wajm/ncbi_error_report.txt'.
If the problem persists, you may consider sending the file
to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
=============================================================

fastq-dump (PID 1609) quit with error code 3

**Comment by wajm** [comment] 2020-05-11 06:33
Same problems here. Thanks.
![스크린샷 2020-05-11 오후 3 32 44](https://user-images.githubusercontent.com/30439753/81530911-bdfee000-939c-11ea-9ef1-ae8b6f4976a1.png)

**Comment by klymenko** [comment] 2020-05-19 14:36
If you have network errors: try our latest 2.10.6 toolkit.
We made some network-related improvements.

**Comment by candacechan** [comment] 2020-05-19 22:04
I am using 2.10.6 ubuntu64 toolkit, getting the same error code.
`
fastq-dump quit with error code 3
`
`2020-05-19T20:28:22 fastq-dump.2.10.6 err: data corrupt while selecting function within transform module - failed SRR7699778
`
`
2020-05-19T20:47:50 fastq-dump.2.10.6 err: transfer canceled while allocating buffer within file system module - Cannot KHttpFileTimedReadChunked: to=480
`

**Comment by isidroc** [comment] 2020-05-19 22:06
I am getting the same error (also using 2.10.6)

**Comment by klymenko** [comment] 2020-05-19 22:09
@isidroc , try the following:
`prefetch SRR7699778 && fastq-dump SRR7699778`

N.B.: fastq-dump will write to current directory;
prefetch will download either to current directory or user repository - depending on your configuration.

**Comment by candacechan** [comment] 2020-05-20 04:29
> 
> 
> @isidroc , @candacechan, try the following:
> `prefetch SRR7699778 && fastq-dump SRR7699778`
> 
> N.B.: fastq-dump will write to current directory;
> prefetch will download either to current directory or user repository - depending on your configuration.

Problem solved, thank you!

**Comment by isidroc** [comment] 2020-05-20 23:24
I can confirm that if one redownloads the sra files using prefetch (sra tools verson 2.10.6), then fasterq-dump works well. It does not work however using sra files downloaded with previous version (I was using 2.10.5). Thanks

**Comment by klymenko** [comment] 2020-05-27 19:20
We had a bug that some runs were not resolved correctly.
It was fixed in release 2.10.7.
Therefore wrong files were saved when caching/downloading such runs.

**Comment by jmerkin** [comment] 2020-06-11 11:59
I am having the same issue with 2.10.7.

**Comment by Maarten-vd-Sande** [comment] 2020-06-30 13:05
Just here to ping that I also have it with 2.10.7

**Comment by bredelings** [comment] 2020-07-17 21:44
This issue continues with 2.10.8, and is _not_ fixed by doing the prefetch:
```
$ prefetch ERR695638
2020-07-17T21:42:15 prefetch.2.10.8: 1) Downloading 'ERR695638'...
2020-07-17T21:42:15 prefetch.2.10.8:  Downloading via HTTPS...
$ fasterq-dump ERR695638
2020-07-17T21:43:01 prefetch.2.10.8:  'ERR695638' is valid
2020-07-17T21:43:01 prefetch.2.10.8: 1) 'ERR695638' was downloaded successfully
2020-07-17T21:43:01 prefetch.2.10.8: 'ERR695638' has 0 unresolved dependencies
2020-07-17T21:43:02 fasterq-dump.2.10.8 err: row#5567 : bits=32, boff=0, len=0 
2020-07-17T21:43:02 fasterq-dump.2.10.8 err: row#117221 : bits=32, boff=0, len=0 
2020-07-17T21:43:05 fasterq-dump.2.10.8 err: row#108744 : bits=32, boff=0, len=0 
fasterq-dump quit with error code 3
```

**Comment by wraetz** [comment] 2020-07-20 15:08
Your second command "fasterq-dump ERR695638" does not use the accession you downloaded via prefetch. By specifying a bare accession the tool always goes out over the internet and fetches the data again - in other words - it ignores your prefetched data. The right way to specify a local copy instead is to give fasterq-dump a local path.

example:

$fasterq-dump ./ERR695634

or

$fasterq-dump /full/path/to/download/ERR685634

The tool internally is looking for slashes in the path. If there are no slashes - it retrieves it remotely...

**Comment by wraetz** [comment] 2020-07-20 15:46
The accession ERR695638 has been loaded with pacbio-load. Such accessions cannot be used with fasterq-dump. Fasterq-dump is written to detect such accessions and inform the user to use fastq-dump instead. We are investigating why this does not happen with this accession.

Please use fastq-dump on ERR695638.

**Comment by dezordi** [comment] 2020-10-02 18:00
Hey guys, I had presented the same error many times, independently of SRA access. I fix it changing the prefetch on SRA configuration from user-repository to current directory.

`vdb-config -i`

![Screenshot from 2020-10-02 14-58-43](https://user-images.githubusercontent.com/16391255/94954712-e1e3cf00-04bf-11eb-8465-f8462d14f1e8.png)

**Comment by moritzschaefer** [comment] 2020-10-18 00:27
@dezordi didn't fix it for me..

**Comment by azzaea** [comment] 2020-12-07 16:41
Chiming in-
I'm also getting the same error downloading from the dataset. While `prefetch` worked, following by `fastq-dump`  still did not fix it though (I was running `parallel-fastq-dump` not `fasqer-dump`). I also reported [here](https://github.com/rvalieris/parallel-fastq-dump/issues/30#issuecomment-739975395)

```
$ parallel-fastq-dump -V
parallel-fastq-dump : 0.6.6

"fastq-dump" version 2.10.8

$ prefetch --max-size 100GB SRR9070264

2020-12-07T10:22:02 prefetch.2.10.8: 1) Downloading 'SRR9070264'...
2020-12-07T10:22:02 prefetch.2.10.8:  Downloading via HTTPS...
2020-12-07T10:22:02 prefetch.2.10.8:    Continue download of 'SRR9070264' from 37942800152
2020-12-07T13:48:11 prefetch.2.10.8:  HTTPS download succeed
2020-12-07T13:48:11 prefetch.2.10.8:   verifying 'SRR9070264'...
2020-12-07T13:56:26 prefetch.2.10.8:  'SRR9070264' is valid
2020-12-07T13:56:27 prefetch.2.10.8: 1) 'SRR9070264' was downloaded successfully
2020-12-07T13:56:27 prefetch.2.10.8: 'SRR9070264' has 0 unresolved dependencies

$ fastq-dump SRR9070264
2020-12-07T16:25:42 fastq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2020-12-07T16:25:42 fastq-dump.2.10.8 err: storage exhausted while writing file within file system module - failed SRR9070264
2020-12-07T16:25:42 fastq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'

=============================================================
An error occurred during processing.
A report was generated into the file '/home/azzaea/ncbi_error_report.txt'.
If the problem persists, you may consider sending the file
to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
=============================================================

fastq-dump quit with error code 3
```

**Comment by kwrodarmer** [comment] 2020-12-07 16:59
The logging output of SRA Tools can be somewhat cryptic. But in this case it's fairly clear:
```
storage exhausted while writing file within file system module
```
It means you're out of disk space. The usage docs in our Wiki (https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump) give some guidance on how much disk space you should make available for processing.

**Comment by klymenko** [comment] 2020-12-18 16:31
@danieldanciu, do you still need help?

**Closed** 2020-12-28 20:22 UTC

**Comment by imperioso94** [comment] 2021-06-01 07:10
hi, i have the same problem with error 3 code with fastq-dump, fsterq-dump, version 2.11.0 and prefetch it's not going anywhere:
2021-06-01T06:54:44 prefetch.2.11.0: 1) Downloading 'SRR5507557'...
2021-06-01T06:54:44 prefetch.2.11.0:  Downloading via HTTPS...

**Comment by roni-fultheim** [comment] 2021-07-13 11:43
also got this error 3 code with fasterq-dump when dowloading from dbGaP.
using fastq-dump solved the problem

Please advise why this happens and how to fix permenantly.

Does this have to do with existance of .vdbcache.sra files?

**Comment by klymenko** [comment] 2021-11-03 17:59
@imperioso94, add `-p` to `prefetch` to see download progress.

@roni-fultheim, create another issue if you need help.

**Comment by jsharbrough** [comment] 2022-05-19 00:32
prefetch $SRA && fasterq-dump -pe 24 ./$SRA 

worked nicely for me, using sratools.2.11.0 on Unix Red Hat 7.6

**Comment by idibaps001** [comment] 2022-12-10 17:14
Hello!

I also meet the error code 3:

7@sllogin2:~/chipseq/raw_data/SRRCD8_mouse> fasterq-dump -e 12 SRR*
2022-12-10T16:52:36 fasterq-dump.2.11.0 err: cmn_iter.c cmn_open_db().VPathRelease( 'SRR2075567' ) -> RC(rcVFS,rcPath,rcReleasing,rcRange,rcExcessive) 
2022-12-10T16:52:36 fasterq-dump.2.11.0 err: invalid accession 'SRR2075567'
fasterq-dump quit with error code 3

7@sllogin2:~/chipseq/raw_data/SRRCD8_mouse>fasterq-dump -e 8 SRRCD8_mouse
2022-12-10T16:40:47 fasterq-dump.2.11.0 err: extract_acc2( 'SRRCD8_mouse' ).VFSManagerExtractAccessionOrOID() -> RC(rcVFS,rcPath,rcConstructing,rcParam,rcIncorrect)
2022-12-10T16:40:47 fasterq-dump.2.11.0 err: invalid accession 'SRRCD8_mouse'
fasterq-dump quit with error code 3

Is there anyone know how to solve this problem?
Thanks!

**Comment by plaquette** [comment] 2023-04-17 10:13
i have the same issue...


(i have an ugly work around - nonetheless, a fix would be appreciated)

**Comment by metehaansever** [comment] 2023-06-08 16:13
If you are using a multithread structure, this can also cause this problem.

**Comment by mesenquima** [comment] 2025-01-17 04:57
Had the same error and the only thing that worked for me was including the path to the file. i.e:

fastq-dump path/to/file.sra
also
fasterq-dump path/to/file.sra

It even worked using specifications (fastq-dump --split-files --origfmt --gzip path/to/file.sra)
