### ISSUE TITLE
prefetch issue

### ISSUE THREAD

**Issue by Phlya** [ncbi/sra-tools#100] opened 2017-10-31 10:39 UTC
Hello,

I am trying to download a lot of sra files to subsequently dump fastq files form them (seems to be much faster than doing fastq-dump directly, especially with parallel-fastq-dump). I am doing it on an SGE cluster, and create a separate job for each SRR. For many of the files (but not all!) I get a strange error: 

`2017-10-31T09:28:50 prefetch.2.8.2 int: incomplete while <INVALID-CONTEXT> within network system module - Ü: Cannot KStreamRea`

With just this in stdout:
```
2017-10-31T09:25:47 prefetch.2.8.2: 1) Downloading 'SRR5339749'...
2017-10-31T09:25:47 prefetch.2.8.2:  Downloading via https...
2017-10-31T09:28:50 prefetch.2.8.2: 1) failed to download SRR5339749
```

For example, it worked for SRR5339748... Which are different files from the same GEO sample! 9/14 samples from there give this error.

This is my download script:
```
#!/bin/sh
# Grid Engine options (lines prefixed with #$)
#$ -cwd
#$ -N dumping
#$ -l h_rt=6:00:00
#$ -l h_vmem=1G
#$ -pe sharedmem 4
. /etc/profile.d/modules.sh
module load anaconda/2.3.0
module load igmm/apps/sratoolkit/2.8.2-1
source activate Hi-C

prefetch $1 &&
parallel-fastq-dump --sra-id $1 --threads 4 --outdir . --split-files --gzip &&
rm /exports/eddie/scratch/s1529682/tmp/sra/sra/$1.sra
```

Would appreciate any advice.

**Comment by kwrodarmer** [comment] 2017-10-31 13:40
This is quite interesting! Can you reproduce the error and give us the exact and complete output over however many lines?

**Comment by Phlya** [comment] 2017-10-31 14:25
If by reproduce you mean by running the script for the same SRR and consistently getting an error, I am trying it now. I can also try it from my personal computer for one or two files, if you want?

The output I show in the first post is everything I get (since it's an SGE job the output goes into separate files for stdout and stderr, I showed both).

**Comment by kwrodarmer** [comment] 2017-10-31 14:28
Yes, the same SRR and consistent error - I'd be interested in the exact output and whether it is consistent. What you showed demonstrates a likely memory corruption that we've never seen before.

The reason I asked is that the output you posted appears truncated. If it is everything you get, then obviously there's nothing more to post.

**Comment by Phlya** [comment] 2017-10-31 14:31
OK, I am trying the same file for which I showed the output right now, I'll let you know how it's going.

Yep, that's the whole output I get, sorry.

**Comment by Phlya** [comment] 2017-10-31 14:33
OK, so I tried the same file again just now, and it works fine, it seems...

**Comment by kwrodarmer** [comment] 2017-10-31 14:37
Okay - interesting. I'd suggest that you not create a large number of prefetch jobs since network bandwidth has an upper limit, and you can easily trigger getting blacklisted, since whether intentional or not, such an aggressive download request behaves a lot like an attack. It's fine to run your conversions in parallel, but keep the number of parallel prefetches within some reasonable limit.

Incidentally, we will be releasing a tool to perform whole-run fastq conversions with greater performance, at the cost of more memory.

**Comment by Phlya** [comment] 2017-10-31 14:40
OK, thanks - how many do you reckon is the upper limit for number of prefetches?

The new tool sounds promising!

**Comment by kwrodarmer** [comment] 2017-10-31 14:50
The answer depends upon whether you're using Aspera or HTTPS. For HTTPS, you can probably run 100 in parallel (but I need to check with our network team). For Aspera, I wouldn't run more than 5.

**Comment by Phlya** [comment] 2017-10-31 14:56
OK, I was running it as https (because I'm not sure how to set up an Aspera command on the cluster), and it was less than 100 downloads - at most around 80.

But do you think this could in principle be the reason for the problem?

**Comment by kwrodarmer** [comment] 2017-10-31 15:04
I can't be sure without checking logs. If you have a large number of files to download, using Aspera would be a reasonable approach. You get much greater throughput, but as a result you can't run so many at once. If you were running 80 in parallel over HTTPS, then there may be other issues at play.

**Comment by Phlya** [comment] 2017-10-31 16:30
So, I tried to do the same but only with 8 jobs, and still I get the same error with some files.

**Comment by Phlya** [comment] 2017-10-31 17:13
However this is definitely not a consistent problem, I just re-started the same scripts, and some of the files that were not downloaded worked. I guess could just iteratively do this until everything works, but it is a pain, obviously.

**Comment by kfuku52** [comment] 2018-02-08 22:16
Today I got the same error when I tried prefetch several sra files with https. Download seemed to start correctly as a temporary file was created (and can continue to several Gb) but it was automatically deleted before download completion with the "<INVALID-CONTEXT>" error. This was consistently occurred over several trials today. Fortunately this problem did not persist in the aspera connection.

**Comment by kwrodarmer** [comment] 2018-02-08 22:37
could you send the log output showing "INVALID-CONTEXT"? If it contains sensitive information, you can send it to sra-tools@ncbi.nlm.nih.gov

**Comment by kfuku52** [comment] 2018-02-08 23:24
Sure. The prefetch command is:
```
prefetch --force no --transport http --max-size 100G SRR1170074
```

stdout:
```
2018-02-08T22:45:07 prefetch.2.8.2: 1) Downloading 'SRR1170074'...
2018-02-08T22:45:07 prefetch.2.8.2:  Downloading via https...
2018-02-08T22:48:18 prefetch.2.8.2: 1) failed to download SRR1170074
```

stderr:
```
2018-02-08T22:48:18 prefetch.2.8.2 int: incomplete while <INVALID-CONTEXT> within network system module - h
```

Interestingly, "`h`" appears to be generated randomly. I got different characters every time.

**Comment by kwrodarmer** [comment] 2018-02-08 23:28
okay - that's clearly a prefetch bug. Can you run the tool `test-sra` from the same working directory and send the output to sra-tools@ncbi.nlm.nih.gov ?

`test-sra SRR1170074 > test-sra.out.txt`

Thank you!

**Comment by kwrodarmer** [comment] 2018-02-08 23:31
Incidentally, I just ran the command without problems. I'm guessing you may have a disk-space issue.

**Comment by kfuku52** [comment] 2018-02-08 23:43
I have no idea how a disk-space issue troubles https but not aspera. Anyway, I just sent the test-sra output. Please check your inbox.

**Comment by kwrodarmer** [comment] 2018-02-09 17:28
We are reviewing the output now, thank you.

**Comment by mbelmadani** [comment] 2018-04-06 21:09
I'm currently hitting the same issue, stdout outputs the same as the prefetch error message above, but in my stderr logs I also see:

I'm simply trying to download some .sra that are under access control (our lab has approval and I've manage to download a few .SRA from the same project before this started happening).

```
2018-04-06T20:51:15 prefetch.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2018-04-06T20:51:15 prefetch.2.8.2 int: error unknown while reading file within network system module - ��: Cannot KStreamR
2018-04-06T20:21:25 prefetch.2.8.2 err: process failed while waiting process - ascp failed with 1
2018-04-06T20:39:55 prefetch.2.8.2 err: process failed while waiting process - ascp failed with 1
2018-04-06T20:50:09 prefetch.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2018-04-06T20:50:09 prefetch.2.8.2 int: error unknown while reading file within network system module - 
2018-04-06T20:21:56 prefetch.2.8.2 err: process failed while waiting process - ascp failed with 1
2018-04-06T20:39:55 prefetch.2.8.2 err: process failed while waiting process - ascp failed with 1
2018-04-06T20:49:34 prefetch.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2018-04-06T20:49:34 prefetch.2.8.2 int: error unknown while reading file within network system module - �#
                                                                                                          : Cannot KStreamRea
```

No idea about the weird characters but that's more or less it  comes out on my terminal.

Is there a recommendation to debug this?

**Comment by klymenko** [comment] 2018-04-09 12:33
There is a bug when prefetch is reporting HTTP errors. It will be fixed in the next release of SRA toolkit.

**Comment by kwrodarmer** [comment] 2018-04-09 19:01
@mbelmadani , also, can you update to the latest release and rerun the operation to capture the output and send it to sra-tools@ncbi.nlm.nih.gov? Thank you!

**Comment by kylinson** [comment] 2019-06-20 08:22
I got this error too
2019-06-20T02:23:28 prefetch.2.9.6: 1) Downloading 'SRR7759704'...
2019-06-20T02:23:28 prefetch.2.9.6:  Downloading via https...
2019-06-20T03:30:16 prefetch.2.9.6 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: 0����
2019-06-20T03:30:16 prefetch.2.9.6:  https download failed
2019-06-20T03:30:16 prefetch.2.9.6: 1) failed to download SRR7759704
how can I just keep retring while not losing my downloaded data?

**Comment by zr0719** [comment] 2019-12-07 08:03
I met this error too.

**Comment by drharishkpbiotek** [comment] 2020-01-07 10:35
I am also getting this error too 
2020-01-07T06:56:59 prefetch.2.9.3: 1) Downloading 'SRR5010461'...
2020-01-07T06:56:59 prefetch.2.9.3:  Downloading via https...
2020-01-07T07:56:42 prefetch.2.9.3 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-1/SRR5010461/SRR5010461.1
2020-01-07T07:56:42 prefetch.2.9.3: 1) failed to download SRR5010461
please can you give solution for this?

**Comment by kwrodarmer** [comment] 2020-01-07 13:24
Yes - please use the latest software. The reason for the need to update your software is that the systems it needs to access are changing and require changes in the underlying networking software.

The failures you observe are not bugs in SRA Toolkit software. The changes we have made to the 2.10.x series attempt to sidestep the types of errors that have increased with new infrastructure. Note that at this moment 2.10.x is only available for Linux.

**Comment by orangeSi** [comment] 2020-02-17 12:24
I fixed it by ```$ vdb-config -s /libs/kns/connect/timeout=200000 ``` just now!

**Comment by grst** [comment] 2020-02-20 10:17
Same here: 
```
Command executed:                                                   

  # max size: 1TB                                                   
  prefetch --progress 1 --max_size 1024000000 SRR9835607            

Command exit status:                                                
  3                                                                 

Command output:                                                     
                                                                    
  2020-02-19T21:05:59 prefetch.2.10.3: 1) Downloading 'SRR9835607'...                                                                    
  2020-02-19T21:05:59 prefetch.2.10.3:  Downloading via https...    
  2020-02-19T21:11:11 prefetch.2.10.3:  https download failed       
  2020-02-19T21:11:11 prefetch.2.10.3: 1) failed to download SRR9835607                                                                  

Command error:                                                      
  2020-02-19T21:11:11 prefetch.2.10.3 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: https://sra-download.ncbi.nlm.nih.gov/traces/sra57/SRR/009605/SRR9835607
```

**Comment by kwrodarmer** [comment] 2020-02-20 12:30
Please see https://github.com/ncbi/sra-tools/wiki/06.-Connection-Timeouts for details on tuning timeout behavior for your location.

**Comment by Fnyasimi** [comment] 2020-04-27 12:48
I have followed the thread above @kwrodarmer but I dont seem to find an answer to the error below, kindly assist

```
2020-04-27T12:36:52 prefetch.2.10.3: 1) Downloading 'SRR363406'...
2020-04-27T12:36:52 prefetch.2.10.3:  Downloading via https...
2020-04-27T12:37:02 prefetch.2.10.3:  https download failed
2020-04-27T12:37:02 prefetch.2.10.3: 1) failed to download SRR363406

2020-04-27T12:34:51 prefetch.2.10.3 int: connection not found while validating within network system module - cannot open remote file: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-5/SRR363406/SRR363406.3
2020-04-27T12:35:11 prefetch.2.10.3 int: connection not found while validating within network system module - Cannot KNSManagerMakeClientRequest: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-5/SRR363406/SRR363406.3
```

**Comment by klymenko** [comment] 2020-05-19 02:57
Try our latest 2.10.6 toolkit.

**Comment by dhrpa** [comment] 2020-06-09 09:17
@kwrodarmer I have similar errors like:
 2020-06-03T11:31:28 prefetch.2.9.1 int: transfer incomplete while reading file within network system module - Cannot KStreamRead:......
2020-06-03T22:59:06 prefetch.2.9.1 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76....

I do understand that I need to be using the latest version, which we have updated now. But the ongoing command I got error with was on the older version of the tool kit. 

My question is will restarting the command on the new version lead to restarting of download from the beginning or will it start midway where it stopped? Or do I need to modify the accession id list itself.
Thank you

**Comment by kwrodarmer** [comment] 2020-06-09 12:39
You can stop the old command and restart using the 2.10.7 version of `prefetch` that is capable of incremental download. As long as it is able to locate the previous partial download, version 2.10.7 will resume and complete the process.

**Comment by dhrpa** [comment] 2020-06-09 12:51
@kwrodarmer Thank you very much for your response. I will try doing that.

**Comment by MatthewP-Newbee** [comment] 2020-06-15 02:10
> You can stop the old command and restart using the 2.10.7 version of `prefetch` that is capable of incremental download. As long as it is able to locate the previous partial download, version 2.10.7 will resume and complete the process.

I am using 2.10.7 version but this problem still remains.
```
2020-06-15T01:34:04 prefetch.2.10.7: 1) Downloading 'SRR4344047'...
2020-06-15T01:34:04 prefetch.2.10.7:  Downloading via HTTPS...
2020-06-15T01:59:36 prefetch.2.10.7 err: transfer incomplete while reading file within network system module - Cannot KHttpFileRead
```
More example
```
2020-06-14T23:53:36 prefetch.2.10.7:  Downloading via HTTPS...
2020-06-15T00:21:11 prefetch.2.10.7 err: transfer incomplete while reading file within network system module - Cannot KHttpFileRead
2020-06-15T01:21:59 prefetch.2.10.7 err: transfer incomplete while reading file within network system module - Cannot KHttpFileRead: to=1
2020-06-15T01:32:39 prefetch.2.10.7 err: transfer incomplete while reading file within network system module - Cannot KHttpFileRead: to=2
```

**Comment by sadafhabib** [comment] 2020-06-28 06:40
I am also facing the similar issue. I download about 50% of my required SRA data using prefetch -v -t fasp command. But for the remaining data, the error is 
err: file not found while copying file - cannot download 'SRR7209005' using requested transport

Please help if someone can resolve the issue. I am using sratoolkit.2.9.2 .

**Comment by dhrpa** [comment] 2020-06-28 13:02
@kwrodarmer 
My data download using prefetch stopped midway with errors of the following type: 

2020-06-24T08:30:20 prefetch.2.10.7 err: transfer incomplete while reading file within network system module - Cannot KHttpFileRead
2020-06-25T18:24:37 prefetch.2.10.7 int: connection failed while opening file within cryptographic module - Cannot KNSManagerMakeClientRequest: https://sra-download.ncbi.nlm.nih.gov/traces/era13/ERR/ERR3405/ERR3405903
2020-06-26T15:47:29 prefetch.2.10.7 err: name not found while resolving query within virtual file system module - failed to resolve accession 'ERR3405981' - no data ( 404 )

2020-06-20T16:10:21 prefetch.2.10.7 err: error unknown while reading file within network system module - Cannot KHttpFileRead
2020-06-20T16:11:46 prefetch.2.10.7 int: connection failed while opening file within cryptographic module - cannot open remote file: https://sra-download.ncbi.nlm.nih.gov/traces/sra18/SRR/005279/SRR5405816
2020-06-22T09:44:01 prefetch.2.10.7 err: self NULL while reading file within file system module - Cannot KFileRead 'https://sra-download.ncbi.nlm.nih.gov/traces/sra19/SRR/005279/SRR5405900': sz=3768, to=1920
2020-06-23T21:17:17 prefetch.2.10.7 err: self NULL while reading file within file system module - Cannot KFileRead 'https://sra-download.ncbi.nlm.nih.gov/traces/sra21/SRR/005279/SRR5405757': sz=3768, to=1920
2020-06-25T09:30:11 prefetch.2.10.7 warn: Maximum file size download limit is 20GB
2020-06-28T11:10:30 prefetch.2.10.7 fatal: SIGNAL - Segmentation fault

Can you help me with why this could happen? This is resulted in stop of all my download.

Thank you in advance

**Comment by kwrodarmer** [comment] 2020-06-29 12:07
We had some problems with components in the backend over the weekend.

You can try again. If the problem still occurs, there could be issues with corrupt cache files. So one thing at a time - please try again and write back if there are still problems.

**Comment by Bguinet** [comment] 2020-07-02 06:35
Hello, i'm facin the same kin of issue. 

I'm using the last version of toolkit (`sratoolkit.2.10.8-ubuntu64`)

Here are the command I use : 

`/beegfs/data/bguinet/TOOLS/sratoolkit.2.10.8-ubuntu64/bin/prefetch ERR034187 && /beegfs/data/TOOLS/sratoolkit.2.10.8-ubuntu64/bin/fasterq-dump -t /beegfs/data/Reads/ --threads 10 -f  ERR034187 -O /beegfs/data/Reads/`

**file.out** 
```
2020-07-01T21:38:17 prefetch.2.10.8: 1) Downloading 'ERR034187'...
2020-07-01T21:38:17 prefetch.2.10.8:  Downloading via HTTPS...
2020-07-02T02:11:13 prefetch.2.10.8:  HTTPS download failed
2020-07-02T02:11:13 prefetch.2.10.8: 1) failed to download ERR034187
```
**file.error**
`2020-07-02T02:11:13 prefetch.2.10.8 err: self NULL while reading file within file system module - Cannot KFileRead 'https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-1/ERR034187/ERR034187.4': sz=3768, to=1920`


`/beegfs/data/bguinet/TOOLS/sratoolkit.2.10.8-ubuntu64/bin/prefetch SRR1015522 && /beegfs/data/TOOLS/sratoolkit.2.10.8-ubuntu64/bin/fasterq-dump -t /beegfs/data/Reads/ --threads 10 -f  SRR1015522 -O /beegfs/data/Reads/`


**file.out**
```
2020-07-01T21:38:17 prefetch.2.10.8: 1) Downloading 'SRR1015522'...
2020-07-01T21:38:17 prefetch.2.10.8:  Downloading via HTTPS...
2020-07-02T02:11:20 prefetch.2.10.8:  HTTPS download failed
2020-07-02T02:11:20 prefetch.2.10.8: 1) failed to download SRR1015522
```

**file.error**
```
(base) bguinet@pbil-deb:/beegfs/data/bguinet/these/Genomes/Aphaenogaster_ashmeadi/Mapping$ more Download_job_Aphaenogaster_ashmeadi_SRR1015522.error
2020-07-02T02:11:20 prefetch.2.10.8 err: self NULL while reading file within file system module - Cannot KFileRead 'https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-5/SRR1015522/SRR1015522.2': sz=3768, to=1920
pigz: skipping: /beegfs/data/bguinet/these/Genomes/Aphaenogaster_ashmeadi/Mapping/Reads/SRR1015522* does not exist
```

and I have the same issue for other run (in fact I dowload the read in parallel on a cluster but only one read command / run and the number of run is about only 20). 

Do you have an idea of what is going on ?

**Closed** 2020-07-02 11:53 UTC

**Comment by zbidav** [comment] 2022-03-14 10:12
Unfourtantly I experienced a similar problem with SRA toolkit 2.10.8 version while downloading a SRA file deposited from dbgap. 
`prefetch.2.10.8 -C yes --ngc $NGC_FILE -p $SRR_RUN -O $file_outputDir $KB_SIZE $PREFETCH_ADDITIONAL > /dev/null 2>&1`
Does anyone have an idea :/? I'm a bit hopeless (no issues were with other files from the same project).

**Comment by stineaj** [comment] 2022-03-14 12:20
@zbidav  This sounds like a data problem in the run if all others downloaded correctly. Of course updating to the latest version of the toolkit may solve the problem so we suggest trying that. If there is still an issue with that run, please send the command and include the accession and error messages to sra@ncbi.nlm.nih.gov
