### ISSUE TITLE
ERROR: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.

### ISSUE THREAD

**Issue by zyh2016** [ncbi/sra-tools#786] opened 2023-02-27 09:08 UTC
I have a question when using prefetch 3.0.2 to download on a linux server，there is a trouble: 
Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
How can  I fix it? Should I update my sra-tool?

**Comment by cmatKhan** [comment] 2023-03-04 22:48
I am intermittently having the same problem. More often than not, the `prefetch` command outputs the following:

```
prefetch-orig.3.0.2 --max-size 10000000000 --ngc ../my_cred.ngc mykart.krt 
Downloading kart file 'mykart.krt'
Checking sizes of kart files...

2023-03-04T22:41:10 prefetch-orig.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2023-03-04T22:41:11 prefetch-orig.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2023-03-04T22:41:13 prefetch-orig.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2023-03-04T22:41:14 prefetch-orig.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
...
```

I see this posted in currently open #768 with the comment 'use the current toolkit', which I believe is what I have, and what the OP is using. This is also mentioned in the closed issues #744, #765, #693.

**Comment by stineaj** [comment] 2023-03-07 16:30
Does the command ever complete or exit? Are you ending the process manually? You can add -v up to three times to get a higher verbosity level to monitor if the process is active or stalled.

**Comment by cmatKhan** [comment] 2023-03-07 17:00
The command does complete after ~3000 lines, which is about the number of files I am expecting to pull using this particular cart file.

When it completes, there is no data in the directory -- nothing has been downloaded.

When I add `-vvv`, I get this additional information:

```
2023-03-07T16:53:53 prefetch-orig.3.0.2: 'tools/ascp/disabled': not found in configuration
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking 'ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: 'ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking 'ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: 'ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking '/usr/bin/ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: '/usr/bin/ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking '/usr/bin/ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: '/usr/bin/ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking '/opt/aspera/bin/ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: '/opt/aspera/bin/ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking '/opt/aspera/bin/ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: '/opt/aspera/bin/ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking '/home/chasem/.aspera/connect/bin/ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: '/home/chasem/.aspera/connect/bin/ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: Checking '/home/chasem/.aspera/connect/bin/ascp'
2023-03-07T16:53:53 prefetch-orig.3.0.2: '/home/chasem/.aspera/connect/bin/ascp': not found
2023-03-07T16:53:53 prefetch-orig.3.0.2: KClientHttpOpen - connected from '65.254.100.81' to locate.ncbi.nlm.nih.gov (165.112.7.16) 
2023-03-07T16:53:53 prefetch-orig.3.0.2: Setting up SSL/TLS structure
2023-03-07T16:53:53 prefetch-orig.3.0.2: Performing SSL/TLS handshake... 
2023-03-07T16:53:53 prefetch-orig.3.0.2: KClientHttpOpen - verifying CA cert 
2023-03-07T16:53:53 prefetch-orig.3.0.2: Verifying peer X.509 certificate...
2023-03-07T16:53:53 prefetch-orig.3.0.2: Reading from server...
2023-03-07T16:53:53 prefetch-orig.3.0.2: Reading from server...

...

2023-03-07T16:53:59 prefetch-orig.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2023-03-07T16:53:59 prefetch-orig.3.0.2: KClientHttpOpen - connected from '65.254.100.81' to locate.ncbi.nlm.nih.gov (165.112.7.16) 
2023-03-07T16:53:59 prefetch-orig.3.0.2: Setting up SSL/TLS structure
2023-03-07T16:53:59 prefetch-orig.3.0.2: Performing SSL/TLS handshake... 
2023-03-07T16:53:59 prefetch-orig.3.0.2: KClientHttpOpen - verifying CA cert 
2023-03-07T16:53:59 prefetch-orig.3.0.2: Verifying peer X.509 certificate...
2023-03-07T16:53:59 prefetch-orig.3.0.2: Reading from server...

...
```

I am following the instructions that I can find for downloading this software, and then running `vdb-config -i`. The instructions say that there are no required settings necessary in the config interface. If there are instructions on what `ascp` and `aspera` are, and if that is the problem, I'd appreciate being pointed in the correct direction. As far as I know, form the last time I used this command (about 2 or 3 weeks ago) when it worked, nothing has changed on my system.

**Comment by stineaj** [comment] 2023-03-07 17:18
ascp is the copy program from the Aspera Connect software. It is still used extensively for uploads to dbGaP and SRA but recent changes to our distribution hardware make Aspera not much of a benefit for users downloading data. These messages come up first just because the logic of the prefetch program is to try ascp first and if it is not available to use HTTPS instead. 

I assume you are getting a long list of "Reading from server..." messages? If so that should indicate the files are transferring.

Where are you expecting the downloaded files to be stored? Did you specify a user-repository in the cache menu of vdb-config?

**Comment by cmatKhan** [comment] 2023-03-07 17:26
![image](https://user-images.githubusercontent.com/43553003/223500178-96c17859-d761-4221-b06d-9863b75411ec.png)

When I used this previously, it has meant that the files are downloaded into my `$PWD`, which is `/scratch/mblab/chasem/dbgap`.

I am running the command right now, and yes there are a long list of "Reading from server..." messages.

However, nothing is downloading into my `$PWD`, or into the `ncbi-cache` directory (which is in my `$PWD`):

```
[chasem@login dbgap]$ tree -L 1 .
.
├── all_cart_prj33268_202303061451.krt
├── ncbi_cache
├── phs000007.v33.pht000905.v5.p14.ctpericard1_2005s.var_report.xml
├── prj_33268.ngc
├── sra_prefetch.sh
├── sratoolkit.3.0.2-ubuntu64
└── test_cart_prj33268_202303030808.krt
```

and the ncbi_cache:

```
[chasem@login dbgap]$ tree ncbi_cache/
ncbi_cache/
├── files
├── nannot
├── refseq
├── sra
└── wgs

5 directories, 0 files

```

**Comment by klymenko** [comment] 2023-03-07 22:50
Running `prefetch` with `-vv` will print you the destination path where each file is being downloaded.

**Comment by cmatKhan** [comment] 2023-03-08 14:34
I attached above the result of running `prefetch` with `-vvv`. Presumably `-vv` is a subset of that.

However, after a less than enlightening back and forth with the help-desk, this is what seems to be occurring:

Since I can successfully download subsets of the cart file in question, the following seems to be true:

1. There is a max limit on **the size of the cart itself** -- not just the individual file size. 
    1. This max limit is not documented, as far as I can tell
1. When the cart file exceeds this limit, `prefetch` fails silently

The recommendation from the help desk amounts to:

-  "1TB is large data". Break the cart up into parts. 

That 1TB is considered large is good to know -- that was not my assumption, given the type of data these servers handle. However, how many parts that 1-3TB cart needs to be broken into is apparently subject to guess and check.

If it is the case that there is a max limit on the **cart size** (not individual file), then here are some feature requests:

1. The website interface should not allow a user to create a cart file that exceeds the maximum cart size limit
    1. That limit should be written at the top of the file selector site, something like, "cart files may not exceed `<some limit>`".
    1. If a user selects so many files that the maximum size is exceeded, then when the user clicks "create cart", pop up a modal that says, "The total size of the files selected exceeds the maximum allowed cart size of  `<some limit>`. Some files must be removed before a cart file may be created."

1. As a backup to that, the `prefetch` command should not fail silently on this -- it should check the cart size (possibly through iteration) and then fail with an error message that says, "The cart file describes a set of files which together exceed the maximum single submission allowed download size of `<some limit>`. To address this, create multiple cart files, none of which describe a set of files that exceeds `<some limit>`"

**Comment by klymenko** [comment] 2023-03-08 15:07
`prefetch` does not have limit on the size of the cart.

**Comment by stineaj** [comment] 2023-03-08 18:00
To expand on the last comment, there is no limit for how much prefetch could read from the cart file. But user experience has shown there might be a functional limit to prevent timeouts. Unfortunately that behavior is variable from user to user and between datasets. In the past we have focused primarily on the efficiency of the client-server interactions as the solution but @cmatKhan raises good points on user interface changes that could improve the download process.

**Comment by cmatKhan** [comment] 2023-03-08 21:30
@stineaj, I appreciate that database management, particularly on a scale like this and with truly sensitive data, is hard. I am not trying to nitpick. But I am trying to get data, and this has so far been excruciatingly difficult.

Presumably a timeout implies that at least 1 download at least starts.

That doesn't describe what is actually happening.

What _is_ occurring is that on certain cart files, for example 1 that we created which describes files no greater than 1GB, `prefetch` works. But another cart file, for instance one that describes a great number of files which in total will be somewhere between 1 and 2 TB, with the same settings (including `max-limit` large enough to turn that limit off), produces effusive logs with `-vvv`, none of which indicate ERROR or WARNING, and then seemingly exits successfully without error. However, nothing is downloaded.

I want to be clear: I have set `--max-limit` to anywhere between 100 and 10000 GB just to eliminate that as a possible cause of failure. In one of the code chunks I sent back to the help-desk, I accidentally omitted that line, and was shamed for it. But, I have not actually at any point omitted that setting in trying to grab this data, and unless I am greatly mistaken, any number that is greater than the max file size, regardless of how "unreasonably large" that number is (eg 10000GB), does not matter. I assume this is a if-condition, and I am setting a threshold, that is all.

If there are "unreasonably large" individual files in your database that I shouldn't grab, that is certainly not something that I bear a responsibility of policing.

I am now having seemingly a different issue.

I am running a `cart` with a file that describes genotype data with no single file greater than `25GB`.

It has been running for close to 3 hours with this printing to stdout:

![image](https://user-images.githubusercontent.com/43553003/223853398-ad39d219-6371-4745-975e-556194a5eb89.png)

But again, nothing is downloaded and there is no other error to indicate whether it is worthwhile letting this continue.

At the very least here, what would be helpful is just a bit better feedback from `prefetch` in terms of what is happening so that I can start to diagnose it. If the **cart** is beyond the recommended limit, maybe a `WARNING` from the sounds of it. If the server is timed out, somehow `prefetch` should fail (i realize that might take some effort to program).

As it stands, it is extremely hard to discern from the logging why `prefetch` isn't working.

**Comment by cmatKhan** [comment] 2023-03-08 22:52
and now I am once again trying a different size cart -- this time, one with files between 1GB and 10GB with no binary files -- and I am getting this once again.

Just to reiterate -- this same command just worked (after 4 hours of "Reading from server..." printing to stdout) on a cart describing files between 100GB and 150GB.


# cmd
```
$ ./sratoolkit.3.0.2-ubuntu64/bin/prefetch-orig.3.0.2 -vvv -X 5000GB --ngc prj_33268.ngc genotypes_1GB_to_10GB_no_binary/genotypes_1GB_to_10GB_no_binary_cart_prj33268_202303081712.krt
```

# output
```
2023-03-08T22:47:36 prefetch-orig.3.0.2: heartbeat = 60000 Milliseconds
2023-03-08T22:47:36 prefetch-orig.3.0.2: Seeding the random number generator
2023-03-08T22:47:36 prefetch-orig.3.0.2: Loading CA root certificates
2023-03-08T22:47:36 prefetch-orig.3.0.2: Configuring SSl defaults
Downloading kart file 'genotypes_1GB_to_10GB_no_binary/genotypes_1GB_to_10GB_no_binary_cart_prj33268_202303081712.krt'
Checking sizes of kart files...

2023-03-08T22:47:36 prefetch-orig.3.0.2: 'tools/ascp/disabled': not found in configuration
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking 'ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: 'ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking 'ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: 'ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking '/usr/bin/ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: '/usr/bin/ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking '/usr/bin/ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: '/usr/bin/ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking '/opt/aspera/bin/ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: '/opt/aspera/bin/ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking '/opt/aspera/bin/ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: '/opt/aspera/bin/ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking '/home/chasem/.aspera/connect/bin/ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: '/home/chasem/.aspera/connect/bin/ascp': not found
2023-03-08T22:47:36 prefetch-orig.3.0.2: Checking '/home/chasem/.aspera/connect/bin/ascp'
2023-03-08T22:47:36 prefetch-orig.3.0.2: '/home/chasem/.aspera/connect/bin/ascp': not found
2023-03-08T22:47:37 prefetch-orig.3.0.2: KClientHttpOpen - connected from '65.254.100.81' to locate.ncbi.nlm.nih.gov (165.112.7.16)
2023-03-08T22:47:37 prefetch-orig.3.0.2: Setting up SSL/TLS structure
2023-03-08T22:47:37 prefetch-orig.3.0.2: Performing SSL/TLS handshake...
2023-03-08T22:47:37 prefetch-orig.3.0.2: KClientHttpOpen - verifying CA cert
2023-03-08T22:47:37 prefetch-orig.3.0.2: Verifying peer X.509 certificate...
2023-03-08T22:47:37 prefetch-orig.3.0.2: Reading from server...
2023-03-08T22:47:37 prefetch-orig.3.0.2: Reading from server...
2023-03-08T22:47:37 prefetch-orig.3.0.2: KClientHttpOpen - connected from '65.254.100.81' to locate.ncbi.nlm.nih.gov (165.112.7.16)
2023-03-08T22:47:37 prefetch-orig.3.0.2: Setting up SSL/TLS structure
2023-03-08T22:47:37 prefetch-orig.3.0.2: Performing SSL/TLS handshake...
2023-03-08T22:47:37 prefetch-orig.3.0.2: KClientHttpOpen - verifying CA cert
2023-03-08T22:47:37 prefetch-orig.3.0.2: Verifying peer X.509 certificate...
2023-03-08T22:47:37 prefetch-orig.3.0.2: Reading from server...
2023-03-08T22:47:37 prefetch-orig.3.0.2: KClientHttpOpen - connected from '65.254.100.81' to locate.ncbi.nlm.nih.gov (165.112.7.16)
2023-03-08T22:47:37 prefetch-orig.3.0.2: Setting up SSL/TLS structure
2023-03-08T22:47:37 prefetch-orig.3.0.2: Performing SSL/TLS handshake...
2023-03-08T22:47:37 prefetch-orig.3.0.2: KClientHttpOpen - verifying CA cert
2023-03-08T22:47:37 prefetch-orig.3.0.2: Verifying peer X.509 certificate...
2023-03-08T22:47:37 prefetch-orig.3.0.2: Reading from server...
...
```

And, after submitting that 3 times in a row with the same result -- nothing downloaded, no errors -- i just submitted the exact same command a 4th time and hey! it worked.

There is something wrong. At the very least, the thing that is wrong is the logging.

**Comment by stineaj** [comment] 2023-03-09 14:06
First, there should be no shame from anyone for omitting a needed switch in a command or in the description of unexpected behavior. I offer my apologies for your software experience and your service experience. And very importantly I am glad to hear your download is working. 

The max file size is there mostly to ensure the users understand how much they will be downloading and that the destination has sufficient space. Before adding that switch one of the primary bug reports received was due to the user storage not being able to accommodate the size of the downloads.

In this case the timeout I am referring to is not necessarily from the download itself but instead from the webservice that tells the toolkit the file locations for download requests. The storage location for a file could be on commercial cloud providers or NCBI servers for either public or protected access submissions. In certain situations large cart files can lead to a timeout from that location service.

We will look into the information you provided through the trouble ticket and use that to improve the service. Thank you.

**Comment by cmatKhan** [comment] 2023-03-09 18:59
I'm going to push back on characterizing this as "working", though occasionally one of the cmds does go through and db-gap deigns to serve me some data.

For the vast majority of attempts, `prefetch` fails to "fetch" anything at all, even though it exits successfully and there are no WARNING or ERROR codes reported in the highest verbosity log setting.

It is also totally unclear when waiting for 4 hours whether or not a download will ever actually begin, or if it is just stuck.

I think calling this "working" is a stretch.

**Comment by klymenko** [comment] 2023-03-09 22:25
Add to your `prefetch` command `--order kart` .
It will reduce the wait time before start of the first actual download.

**Comment by cmatKhan** [comment] 2023-03-15 21:01
@taylordm None of the solutions offered by the NCBI help desk, or here, _consistently_ addressed this issue.

However, I can confirm that `prefetch` _sometimes_ works. 

As far as I can tell, the size of the cart has little to no relation to how consistently `prefetch` works, with the caveat that the cart file which I originally tried that describes somewhere between 1 and 2 TB has never pulled data, while subsets of the same cart with files up to ~300GB have.

re: ascp -- I can't make sense out of what the docs say here, but maybe this will make sense to you:

[sratools docs: Avoid using ascp directly for downloads](https://github.com/ncbi/sra-tools/wiki/Avoid-using-ascp-directly-for-downloads)

I believe the log messages re: ascp occur no matter what. What I can say for sure is that whenever my downloads have been successful, they have occurred over HTTPS.

I would encourage you to reach out to the NCBI help desk. Don't let them gaslight you and say that `pretetch` "works". That it mostly doesn't work, at least for certain data (maybe its the datatype? Are you accessing dbgap data?), is a problem.

What I have been harping on is that at the very least, more informative logs would be helpful. I don't know what the issue is, of course, and fixing it may be intensive. But a message in the log that gives some hint that `prefetch` at least recognizes that failing to fetch anything is an error would be nice.

**Comment by klymenko** [comment] 2023-03-31 20:10
Aspera is being disabled.
`prefetch` tries its best but it downloads from the servers.
If the `prefertch` download fails - rerun the same command again and `prefetch` will try to continue or retry the failed downloads.

**Comment by klymenko** [comment] 2023-04-06 17:08
Do you need more help?

**Closed** 2023-04-27 14:50 UTC

**Comment by Han-Cao** [comment] 2023-06-02 02:34
> Add to your `prefetch` command `--order kart` . It will reduce the wait time before start of the first actual download.

I have the same issue and this can fix it.

**Comment by danafton** [comment] 2023-08-12 20:26
Experiencing similar issues as others here. What a terribly cumbersome and buggy platform dbgap is. 

In any case, the workaround I have found for trying to download a large number of files which seems to help is to add "--rows 1-100" at the end of my prefetch command and then cycle through higher row numbers. i.e. I am manually batching things out because in the year 2023 we can't have a computer do this for us.

**Comment by cmatKhan** [comment] 2023-08-12 23:24
@danafton I struggled and struggled with this. I was given some bad advice from NCBI (for instance, that my upper limit on max file size was "unreasonable". This is of course nonsense. The only way to disable to the max file limit is to set a large number, the size of which doesn't matter if the goal is `inf`. My network can  handle it -- the problem wasn't on my side).

What I found is that despite repeatedly not working, if you are persistent an keep resubmitting, eventually it does.

I did end up breaking up my karts into smaller parts. Keeping the plain text tsv of the kart, along with the kart file, is a good idea, of course.

**Comment by amstilp** [comment] 2023-08-23 23:49
@cmatKhan I am having similar issues downloading phenotype data from dbGaP - not even large genomic files - with a max cart size of ~65 Mb. `prefetch` will often fail to download a single file, will sometimes report that it has downloaded a file but doesn't actually download it. In these cases, it never exits with an error code (as it should, in my opinion).

Since I need to script this, I will likely have run `prefetch` in a loop until all files are *actually* downloaded. Were you able to get a tsv of files in the kart file?

**Comment by cmatKhan** [comment] 2023-08-24 10:47
If I misunderstand the question, apologies.

I think what you're asking is: since the download command is so unreliable, and since it seems like the advice from NCBI is to break up the kart file, how do I know that I have actually downloaded all that I want to download?

Basically, how do I audit the download process in the face of so many "errors" (especially those 'silent' errors which don't actually return an error code).

We had the same problem. After getting through ~50% of what we wished to pull, I realized that when we created the kart file, we also *should* have created the plain text tsv along with it. Again, if I am misinterpreting your question, sorry -- when I explained this to my group, their response was, "...and you weren't doing this to begin with?"

In any case, if you keep the `kart` and the `tsv` together, you can audit the download.

If I were to do this again, I think what I'd actually do is first use their site to create the full set that I actually want, and create just a `tsv` of that. I might create the `kart` just for fun, but my experience was that I had to create smaller karts to make the downloads work more reliably. As the downloads proceed (buggily), I'd audit against that master tsv.

**Comment by amstilp** [comment] 2023-08-24 17:23
Thanks @cmatKhan. I saw that I could export a `tsv` from the "Files table" button above, but I was hoping you'd found a clever way to extract it from the `kart` file. Alas.

**Comment by OlivierCoen** [comment] 2023-10-24 10:36
Hi @cmatKhan, I had exactly the same issue as yours.
Prefetch was working inconsistently on SRR ids corresponding to small datasets. 
My assumption is that it must have been a configuration issue but I could not figure out what the problem was.
I managed to have prefetch work every time by using the Docker image provided by NCBI:
[https://hub.docker.com/r/ncbi/sra-tools](url)
and following the setup guidelines here:
[https://github.com/ncbi/sra-tools/wiki/SRA-tools-docker](url)
It's more complex than using prefetch directly, but at least I could download the files I needed

**Comment by OlivierCoen** [comment] 2023-10-24 13:04
Actually I just realized that the SRA toolkit version used in the docker image in 3.0.1, while the version I was using (outside the container) was 3.0.7 (the latest currently).
I downloaded and installed SRA toolkit version 3.0.1 with the provided script ([https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.7/setup-apt.sh](url)), after changing version from 3.0.7 to 3.0.1 in the script file. I did not configure SRA toolkit any further.
Now it's working well, like in the container :)

**Comment by MagpiePKU** [comment] 2023-12-10 17:58
Hi,

I would like to second that I have encountered the same problem with 3.0.7 binary. 

We tested like:

/path_to_sratoolkit.3.0.7-centos_linux64/bin/prefetch -X 5000GB -vvv -t http -f yes SRR10156643

Then it failed without saving anything. 

The output was:

```
2023-12-10T17:58:29 prefetch.3.0.7: heartbeat = 60000 Milliseconds
2023-12-10T17:58:29 prefetch.3.0.7: Seeding the random number generator
2023-12-10T17:58:29 prefetch.3.0.7: Loading CA root certificates
2023-12-10T17:58:29 prefetch.3.0.7: Configuring SSl defaults

2023-12-10T17:58:40 prefetch.3.0.7: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
```
